#!/usr/bin/env bash
# Bash script that Install nginx on your web-01 server and requirements
apt-get update -y
apt-get install nginx -y
sudo sed -i 's/\(listen \[::\]:80;\)/# \1\nlisten 80;/' /etc/nginx/sites-available/default
echo "Hello World!" > /var/www/html/index.html
service nginx restart
