#!/usr/bin/env bash
# Nginx server to /redirect_me is redirecting to a page
sudo apt-get update -y
sudo apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i "/server {/a \
    location /redirect_me { \
        rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent; \
    }" /etc/nginx/sites-enabled/default

sudo service nginx restart
