#!/usr/bin/env bash                                                           
# Install and configure HAproxy on the given lb-01 server                          
sudo apt-get update
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get update
sudo apt-get -y install haproxy=2.0.\*
sudo service haproxy start
echo " frontend requests
	bind *:80
	default_backend web_servers

backend web_servers
	balance roundrobin
	server 193423-web-01  52.91.119.212:80 check
	server 193423-web-02  100.25.201.99:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
