#!/usr/bin/env bash
# displays numbers 1 to 20 then bad luch in specified places
x=1
while [ $x -le 20 ]
do
	echo $x
	case $x in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
		esac
		((x++))
done
